version: "3.8"
services:
  db:
    build: ./db
    ports:
      - "5432:5432"
  app:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://myuser:mypass@db:5432/mydb
    depends_on:
      - db
